language: python

python:
    - "2.7"
    - "3.2"
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq clang libclang-dev
    - sudo apt-get install -qq libgtest-dev google-mock valgrind
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
    - pip install pytest-cov ply clang

script: 
    - py.test --cov .
    - cd prophy_cpp
    - ./waf configure_test test
