language: python

python:
    - "2.7"
    - "3.4"

env:
    global:
        - CLANG_VER="3.5"
        - GCC_VER="4.8"
    matrix:
        - COMPILER=clang++
        - COMPILER=gcc

install:
    - if [ "$COMPILER" = "gcc" ]; then export CXX="g++-$GCC_VER" CC="gcc-$GCC_VER"; fi
    - if [ "$COMPILER" = "clang" ]; then export CXX="clang++" CC="clang"; fi
    # Install clang dependencies
    - pip install -qq clang==$CLANG_VER
    - export PYTHON_CLANG_DIR=`pip show -f clang | grep -i location | cut -f 2 -d " "`
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 -wno $PYTHON_CLANG_DIR/clang $PYTHON_CLANG_DIR/clang; fi
    - sudo ln -v -s /usr/lib/x86_64-linux-gnu/libclang-$CLANG_VER.so.1 /usr/lib/x86_64-linux-gnu/libclang.so
    - sudo ldconfig
    # Install gtest and gmock dependencies
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
    # prophy dependencies
    - pip install pytest-cov ply

script:
    - py.test --cov .
    - cd prophy_cpp
    - ./waf configure_test test -j1
    - ./waf dist

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise
        - llvm-toolchain-precise-3.5
        packages:
        - gcc-4.8
        - g++-4.8
        - libgtest-dev
        - google-mock
        - valgrind
        - clang-3.5
        - libclang-3.5
        - libclang-3.5-dev

notifications:
    email: false
