language: python

python:
    - "2.7"
    - "3.2"
before_install:
    - sudo apt-add-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" --yes
    - sudo apt-add-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" --yes
    - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" --yes
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key| sudo apt-key add -
    - sudo apt-get update -qq

install:
    - sudo apt-get install --allow-unauthenticated -qq clang-3.5 libclang-3.5 libclang-3.5-dev python-clang-3.5
    - pip install -qq clang==3.5
    - sudo ln -v -s /usr/lib/x86_64-linux-gnu/libclang-3.5.so.1 /usr/lib/x86_64-linux-gnu/libclang.so
    - sudo ldconfig
    - sudo apt-get install -qq libgtest-dev google-mock valgrind
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
    - pip install pytest-cov ply

script:
    - py.test -vv -rxsE --cov .
    - cd prophy_cpp
    - ./waf configure_test test -j1
    - ./waf dist
