language: python

python:
    - "2.7"
    - "3.2"
before_install:
    - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
    - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list
    - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq

install:
    - sudo apt-get install --allow-unauthenticated -qq clang-3.6 libclang-3.6-dev python-clang-3.6
    - sudo apt-get install -qq libgtest-dev google-mock valgrind
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
    - pip install pytest-cov ply

script:
    - py.test -vv -rxsE --cov .
    - cd prophy_cpp
    - ./waf configure_test test -j1
    - cat /home/travis/build/cislaa/prophy/prophy_cpp/build/config.log
    - ./waf dist
