language: python

python:
    - "2.7"
    - "3.2"
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq clang libclang-dev libclang-common libgtest-dev libgtest0 google-mock
    - pip install pytest-cov ply clang

script: 
    - py.test --cov .
    - cd prophy_cpp
    - ./waf configure_test test
