language: python

python:
    - "2.7"
    - "3.2"
before_install:
    - sudo apt-add-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" --yes
    - sudo apt-add-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" --yes
    - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" --yes
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key| sudo apt-key add -
    - sudo apt-get update -qq

install:
    - export CLANG_VER="3.5"
    - sudo apt-get install --allow-unauthenticated -qq clang-$CLANG_VER libclang-$CLANG_VER libclang-$CLANG_VER-dev python-clang-$CLANG_VER
    - pip install -qq clang==$CLANG_VER 2to3
    - export PYTHON_SITE_PACKAGES=`python -m site --user-site`
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 -wno $PYTHON_SITE_PACKAGES/clang $PYTHON_SITE_PACKAGES/clang
    - sudo ln -v -s /usr/lib/x86_64-linux-gnu/libclang-$CLANG_VER.so.1 /usr/lib/x86_64-linux-gnu/libclang.so
    - sudo ldconfig
    - sudo apt-get install -qq libgtest-dev google-mock valgrind
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
    - pip install pytest-cov ply

script:
    - py.test -vv -rxsE --cov .
    - cd prophy_cpp
    - ./waf configure_test test -j1
    - ./waf dist

notifications:
    email: false
